FROM ubuntu
ARG YARA_VERSION
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get -y install git automake libtool make gcc pkg-config bison flex && \
            git clone --recursive --branch v$YARA_VERSION https://github.com/VirusTotal/yara.git && \
            cd yara && \
            ./bootstrap.sh && \
            ./configure && \
            make && \
            make install
