ARG ACCOUNT_NUMBER
ARG STAGE
FROM $ACCOUNT_NUMBER.dkr.ecr.eu-west-2.amazonaws.com/yara:$STAGE
WORKDIR /rules
COPY rule-sources /rules/rule-sources
COPY compile.py /rules/compile.py
RUN apt-get -y update && apt-get -y install python3-dev python3-pip && \
            pip3 install yara-python && \
            cat rule-sources | xargs -n1 git clone && \
            ./compile.py
